# Generated by Django 4.1.4 on 2022-12-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarkpage',
            name='coordinate_latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landmarkpage',
            name='coordinate_longitude',
            field=models.IntegerField(null=True),
        ),
    ]
