# Generated by Django 4.1.4 on 2022-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_landmarkpage_coordinate_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkpage',
            name='coordinate_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landmarkpage',
            name='coordinate_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
